export const FLIGHTS_LIST_LOADING = 'GET_TODO_LIST_LOADING';
export const FLIGHTS_LIST_FAILURE = 'GET_TODO_LIST_FAILURE';
export const FLIGHTS_LIST_SUCCESS = 'GET_TODO_LIST_SUCCESS';
export const CLEAR_FLIGHTS_LIST_DATA = 'CLEAR_TODO_LIST_DATA';
export const BOOK = 'BOOK';
export const CLEAR_API_DATA = 'CLEAR_API_DATA';
